version: "3.1"

services:
    mysql:
        image: mysql:8.0
        container_name: transit-tracker-mysql
        working_dir: /app
        volumes:
            - .:/app
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=transit_tracker
            - MYSQL_USER=transit_tracker
            - MYSQL_PASSWORD=secret
        ports:
            - "8044:3306"

    elasticsearch:
        image: elasticsearch:5.4-alpine
        container_name: transit-tracker-elasticsearch

    web:
        image: nginx:alpine
        container_name: transit-tracker-webserver
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
           - "8042:80"

    php-fpm:
        build: docker/php-fpm
        container_name: transit-tracker-php-fpm
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
